# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productovariacion',
            name='stock',
        ),
    ]
