# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_productovariacion_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('tela', 'Tela'), ('empaque', 'Empaque')], max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='/materiales/')),
            ],
        ),
    ]
