# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0002_auto_20160720_1230'),
        ('catalogo', '0003_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='utiles.Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='talla',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='utiles.Talla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(blank=True, choices=[('tela', 'Tela'), ('empaque', 'Empaque'), ('suela', 'Suela')], max_length=100),
        ),
    ]
