# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20160805_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='ancho',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
