# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:40
from __future__ import unicode_literals

import cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text=b'El titulo de la pagina web', max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('cuerpo', models.TextField(blank=True)),
                ('seccion', models.CharField(blank=True, help_text=b'El id donde se colocara', max_length=100)),
                ('carrusel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(upload_to=cms.models.url_imagen_pr)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCarrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text=b'Titulo que tendra la imagen en el Alt', max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to=b'bloque/carrusel')),
                ('bloque', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='cms.Bloque')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LinkMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('icono', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('template', models.CharField(blank=True, max_length=100)),
                ('seccion', models.CharField(blank=True, help_text=b'El id donde se colocara', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text=b'El titulo de la pagina web', max_length=100)),
                ('descripcion', models.CharField(help_text=b'La descripcion que se vera en la pagina para el buscador', max_length=150)),
                ('titulo_activo', models.BooleanField(default=True)),
                ('front', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('cuerpo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeccionesCMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateBloque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='paginas',
            field=models.ManyToManyField(blank=True, related_name='menus', to='cms.Page'),
        ),
        migrations.AddField(
            model_name='linkmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.Menu'),
        ),
        migrations.AddField(
            model_name='carrusel',
            name='seccion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cms.SeccionesCMS'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='cms.Page'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.TemplateBloque'),
        ),
    ]
