# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='ayuda_no',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='ayuda_si',
        ),
        migrations.AddField(
            model_name='comentario',
            name='ayuda',
            field=models.BooleanField(default=False),
        ),
    ]
