# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0005_material_ancho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Material')),
            ],
        ),
    ]
