# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_material_ancho'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('operacion', models.CharField(choices=[('mas', 'Aumenta'), ('menos', 'Disminuye')], max_length=10)),
                ('total', models.IntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Material')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.ProductoVariacion')),
            ],
        ),
    ]
