# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20160807_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='num_operacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
