# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20160812_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_acumulado',
            field=models.IntegerField(default=0),
        ),
    ]
