# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_carro', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto - Actualmente activa  '), ('Fusionada', 'Fusionada - sustituida por otra canasta '), ('Guardado', 'Guardado - para los articulos para comprar mas adelante '), ('Congelado', 'Congelado - la canasta no se puede modificar '), ('Enviado', 'Enviado - ha sido ordenado en la caja')], default='Abierto', max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaCarro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='carro.Carro')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto')),
                ('variacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.ProductoVariacion')),
            ],
        ),
    ]
