# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_auto_20160720_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineacarro',
            name='producto',
        ),
    ]
